apiVersion: v1
kind: Service
metadata:
  name: nginx-php-svc
spec:
  ports:
    - port: 80
      targetPort: 80
      protocol: TCP
      nodePort: 30001
  selector: 
   web: nginx-php
  type: NodePort 
