apiVersion: v1
kind: Pod
metadata:
  name: web-pod
  labels:
    web: nginx-php
spec:
  containers:
  - name: nginx-php
    image: richarvey/nginx-php-fpm:latest
    ports:
      - containerPort: 80
        hostPort: 80
