apiVersion: v1
kind: ReplicationController
metadata:
  name: nginx-php-rc
spec: 
  replicas: 2
  selector:
    web: nginx-php 
  template: 
    metadata:
      labels:
        web: nginx-php
      name: web-pod
    spec:
      containers:
      - image: richarvey/nginx-php-fpm:latest
        name: web 
        ports:
          - containerPort: 80
